// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: item.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countItemsByOrgID = `-- name: CountItemsByOrgID :one
SELECT COUNT(*) FROM item.items
WHERE org_id = $1
`

func (q *Queries) CountItemsByOrgID(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countItemsByOrgID, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM item.items
WHERE id = $1 AND org_id = $2
`

type DeleteItemParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) DeleteItem(ctx context.Context, arg DeleteItemParams) error {
	_, err := q.db.ExecContext(ctx, deleteItem, arg.ID, arg.OrgID)
	return err
}

const findItemsByOrgID = `-- name: FindItemsByOrgID :many
SELECT id, org_id, name, created_at
FROM item.items
WHERE org_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type FindItemsByOrgIDParams struct {
	OrgID  uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) FindItemsByOrgID(ctx context.Context, arg FindItemsByOrgIDParams) ([]ItemItem, error) {
	rows, err := q.db.QueryContext(ctx, findItemsByOrgID, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemItem
	for rows.Next() {
		var i ItemItem
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, org_id, name, created_at
FROM item.items
WHERE id = $1 AND org_id = $2
`

type GetItemByIDParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) GetItemByID(ctx context.Context, arg GetItemByIDParams) (ItemItem, error) {
	row := q.db.QueryRowContext(ctx, getItemByID, arg.ID, arg.OrgID)
	var i ItemItem
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const insertItem = `-- name: InsertItem :exec
INSERT INTO item.items (id, org_id, name, created_at)
VALUES ($1, $2, $3, $4)
`

type InsertItemParams struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	Name      string
	CreatedAt time.Time
}

func (q *Queries) InsertItem(ctx context.Context, arg InsertItemParams) error {
	_, err := q.db.ExecContext(ctx, insertItem,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const itemExists = `-- name: ItemExists :one
SELECT EXISTS(
    SELECT 1 FROM item.items
    WHERE id = $1 AND org_id = $2
)
`

type ItemExistsParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) ItemExists(ctx context.Context, arg ItemExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, itemExists, arg.ID, arg.OrgID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateItem = `-- name: UpdateItem :exec
UPDATE item.items
SET name = $1
WHERE id = $2 AND org_id = $3
`

type UpdateItemParams struct {
	Name  string
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) error {
	_, err := q.db.ExecContext(ctx, updateItem, arg.Name, arg.ID, arg.OrgID)
	return err
}
