// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountItemsByOrgID(ctx context.Context, orgID uuid.UUID) (int64, error)
	DeleteItem(ctx context.Context, arg DeleteItemParams) error
	FindItemsByOrgID(ctx context.Context, arg FindItemsByOrgIDParams) ([]ItemItem, error)
	GetItemByID(ctx context.Context, arg GetItemByIDParams) (ItemItem, error)
	InsertItem(ctx context.Context, arg InsertItemParams) error
	ItemExists(ctx context.Context, arg ItemExistsParams) (bool, error)
	UpdateItem(ctx context.Context, arg UpdateItemParams) error
}

var _ Querier = (*Queries)(nil)
